### ISSUE TITLE
If I dont want to use patternPrefix and helperPrefix, 

### ISSUE THREAD

**Issue by nicholaslee119** [namics/stylelint-bem-namics#4]
Is there any way to configure that?

**Comment by ernscht** [comment]
No, currently this is not possible.
But we are open for suggestions.

**Comment by ernscht** [comment]
Thanks a lot for your PR.

I was not shure what you wanted to achieve exactly.
As i understand you now - with your boolean switch you still allow prefixes. Selectors like `.block`, `.block__element` are valid as well as `.a-block` and `a-block__element`, ...
We could also call them block names. So far so good.

Because the prefixes are a core concept in our naming convention your PR results in some inconsistencies.

* The selector `-block` is rejected with the misleading message: "Expected class name "-block" to use the [prefix]-[block] syntax."
* The selector `--block` is rejected with the message: "Expected class name "--block" to use the [prefix]-[block]--[modifier] syntax."
* The selctor `m--modifier` shouldn't be rejected (it's rejected because `m` is a default prefix).
* `state-m--state`, 'state-m-block' or `m--modifier__block` are also rejected because of the default configuration
* ...

We're not at the end ;-)

and...
What do you think about disabling the individual configuration parameters?

```json
"plugin/stylelint-bem-namics": {
    "patternPrefixes": false,
    "helperPrefixes": false,
}
```

**Comment by nicholaslee119** [comment]
Thanks for your explaining,
Actually, I was also considering those situations which you just mention, 
When I recognize If we want to handle all the situation,  we should refactor the function of parseClassName to let it parse class name into an object which is holding namespace/helper-prefix/pattern-prefix no matter if these prefixes exist.
but I was little rush to close those prefixes for my own needs, sorry for that.

and

I think it is a good idea to disabling the individual config in that way.

**Comment by ernscht** [comment]
hope this commit will fit your needs.

small change in configuration:
```
"plugin/stylelint-bem-namics": {
    "patternPrefixes": [],
    "helperPrefixes": [],
}
```

**Comment by ernscht** [comment]
[Version 4.0.0](https://github.com/namics/stylelint-bem-namics/releases/tag/4.0.0) released

**Comment by nicholaslee119** [comment]
That is great! Thank you
